# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  encoding: unicode
  database: shortly_dev
  pool: 5
  username: dev
  password: 123
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: tiny
  pool: 5
  username: tiny
  password: 123
  host: localhost